FROM golang:1.19 AS back_compiler

# set working directory 
WORKDIR /GoFiles/

# copy code 
COPY ./ .

# build executable
RUN go build -o /executable/webapi ./cmd/webapi

# final container image
FROM debian:bullseye

# set working directory
WORKDIR /executable/

# copy executable from the builder stage
COPY --from=back_compiler /executable/webapi ./

# ports
EXPOSE 3000 4000

# command to run 
CMD ["/executable/webapi"]
